# Generated by Django 3.2.16 on 2022-11-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='content',
        ),
    ]
