# Generated by Django 3.2.16 on 2022-11-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
